name: hi mom workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hi mom
        run: echo "hi mom from echo"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye mom
        run: echo "goodbye mom from echo"
        shell: bash